# Generated by Django 3.2.16 on 2023-01-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image1', models.FileField(upload_to='media/input')),
                ('image2', models.FileField(upload_to='media/input')),
                ('final_image', models.FileField(upload_to='media/output')),
            ],
        ),
    ]
