# Generated by Django 3.2.16 on 2023-01-21 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20230121_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload2',
            name='final_image',
        ),
        migrations.RemoveField(
            model_name='upload2',
            name='image2',
        ),
    ]
