# Generated by Django 3.2.16 on 2023-01-21 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20230121_1447'),
    ]

    operations = [
        migrations.DeleteModel(
            name='upload',
        ),
        migrations.DeleteModel(
            name='Upload2',
        ),
    ]
