# Generated by Django 3.2.16 on 2023-01-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_upload_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='image2',
            field=models.FileField(default='myapp/input/Nehas_Resume_3.pdf', upload_to='myapp/input'),
        ),
    ]
