# Generated by Django 3.2.16 on 2023-01-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20230121_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='image1',
            field=models.FileField(default='myapp/input/Nehas_Resume_3.pdf', upload_to='myapp/input'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='image2',
            field=models.FileField(default='myapp/input/Nehas_Resume_3.pdf', upload_to='myapp/input'),
        ),
    ]
