# Generated by Django 3.2.16 on 2023-01-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_upload_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='image2',
            field=models.FileField(upload_to='myapp/input'),
        ),
    ]
