# Generated by Django 3.2.16 on 2023-01-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20230121_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='final_image',
            field=models.ImageField(null=True, upload_to='myapp/output'),
        ),
    ]
